# Usa la porta 5432 per connessione diretta, o 6543 se attivi il Pooling
spring.datasource.url=jdbc:postgresql://db.panbgxyffqcgixsttsbl.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=CEDeasy1642026
spring.datasource.driver-class-name=org.postgresql.Driver

# Ottimizzazioni JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://panbgxyffqcgixsttsbl.supabase.co/auth/v1
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://panbgxyffqcgixsttsbl.supabase.co/auth/v1/.well-known/jwks.json

logging.level.org.springframework.security=DEBUG