# application-dev.properties (PULITO)
spring.datasource.url=jdbc:postgresql://db.panbgxyffqcgixsttsbl.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=CEDeasy1642026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://panbgxyffqcgixsttsbl.supabase.co/auth/v1
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://panbgxyffqcgixsttsbl.supabase.co/auth/v1/.well-known/jwks.json

logging.level.org.springframework.security=DEBUG