/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/approved` | `/approved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(smm)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(smm)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(smm)'}/brands` | `/brands`; params?: Router.UnknownInputParams; } | { pathname: `${'/(smm)'}/brands/[brandId]` | `/brands/[brandId]`, params: Router.UnknownInputParams & { brandId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/approved` | `/approved`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(smm)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(smm)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(smm)'}/brands` | `/brands`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(smm)'}/brands/[brandId]` | `/brands/[brandId]`, params: Router.UnknownOutputParams & { brandId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/approved${`?${string}` | `#${string}` | ''}` | `/approved${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(client)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(smm)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(smm)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(smm)'}/brands${`?${string}` | `#${string}` | ''}` | `/brands${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/approved` | `/approved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(smm)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(smm)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(smm)'}/brands` | `/brands`; params?: Router.UnknownInputParams; } | `${'/(smm)'}/brands/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/brands/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(smm)'}/brands/[brandId]` | `/brands/[brandId]`, params: Router.UnknownInputParams & { brandId: string | number; } };
    }
  }
}
